#! /bin/bash

if [ "$1" = "-y" ];
then
	OVERWRITE="yes";
elif [ "$1" = "--version" ];
then
	echo "0.1.0"
	echo "This program is licensed under the GNU GPL, it is free software, and can be modified and redistributed."
	echo "This program is offered WITHOUT warranty to the extent allowed by applicable law"
fi

SRC=$1;
DEST=$2;

TODAY=$(date '+%y%m%d'); #get the date as a number in the form of ymd
TODAY_READABLE=$(date '+%m,%d,%y'); #get the date as the folder name will be m,d,y

LAST_BACKUP=$( ls $DEST | sed 's/^\(.*\),\(.*\),\(.*\)$/\3\1\2/g' | sort -nr | head -1); #get the last backup,
#as a number in the form of ymd

LAST_BACKUP_READABLE=$(echo $LAST_BACKUP | sed 's/^\([0-9]\{2\}\)\([0-9]\{2\}\)\([0-9]\{2\}\)$/\2,\3,\1/g'); #get the last
#backup as it is in the file name m,d,y

if [ "$(ls $DEST)" = "" ];
then 

	mkdir $DEST/$TODAY_READABLE
	OUT=$(rsync -r  --progress -H $SRC $DEST/$TODAY_READABLE)

	if [ "$?" != "0" ];
	then
		exit $?
	fi

       echo $OUT | sed 's/[[:space:]+][0-9]*[[:space:]+]\([0-9]\{1,3\}\)%.*/\1/g' | grep '^[[:space:]]*[0-9]\{1,3\}$' | sed 's/^[[:space:]]*\([0-9]\{1,3\}\)$/\1/g';
else
	if [ "$LAST_BACKUP" = $TODAY ];
	then

		if [  -z "$OVERWRITE" ];
		then
			echo "backup already completed for today, overwrite? [yes/no]"
			read OVERWRITE;
		fi
		
		if [ "$OVERWRITE" = "yes" ];
		then
			rm -rf $DEST/$LAST_BACKUP_READABLE;
			mkdir $DEST/$TODAY_READABLE;
			OUT=$(rsync -r --progress $SRC $DEST/$TODAY_READABLE)
		       
			if [ "$?" != "0" ];
			then
				exit $?
			fi

			echo $OUT | sed 's/[[:space:]+][0-9]*[[:space:]+]\([0-9]\{1,3\}\)%.*/\1/g' | grep '^[[:space:]]*[0-9]\{1,3\}$' | sed 's/^[[:space:]]*\([0-9]\{1,3\}\)$/\1/g';

		else #doesn't want to overwrite
			exit 1;
		fi

		exit 0;

	else #last backup was yesterday

		mkdir  $DEST/$TODAY_READABLE

		OUT=$(rsync -avz --progress --link-dest=$(pwd)/$DEST/$LAST_BACKUP_READABLE $SRC/ $DEST/$TODAY_READABLE )
		
		if [ "$?" != "0" ];
		then
			exit $?
		fi

		echo $OUT | sed 's/[[:space:]+][0-9]*[[:space:]+]\([0-9]\{1,3\}\)%.*/\1/g' | grep '^[[:space:]]*[0-9]\{1,3\}$' | sed 's/^[[:space:]]*\([0-9]\{1,3\}\)$/\1/g' ;
	fi
fi
